# Generated by Django 6.0.3 on 2026-04-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default="contact@shivaservices.co.in", max_length=254
                    ),
                ),
                ("phone", models.CharField(default="+91 8000 951 195", max_length=20)),
                (
                    "address",
                    models.TextField(default="123 Business Avenue, Tech Park, City"),
                ),
                (
                    "facebook_url",
                    models.URLField(
                        blank=True, help_text="Facebook Profile/Page URL", null=True
                    ),
                ),
                (
                    "twitter_url",
                    models.URLField(
                        blank=True, help_text="Twitter Profile URL", null=True
                    ),
                ),
                (
                    "instagram_url",
                    models.URLField(
                        blank=True, help_text="Instagram Profile URL", null=True
                    ),
                ),
                (
                    "linkedin_url",
                    models.URLField(
                        blank=True, help_text="LinkedIn Profile URL", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
