# Generated by Django 6.0.3 on 2026-04-07 16:44

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="The sequence number on the journey (0, 1, 2, etc.)",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="e.g. 'The Gateway'", max_length=200),
                ),
                (
                    "eyebrow",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'Shiva Services - Est 2024'",
                        max_length=100,
                    ),
                ),
                (
                    "content",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        help_text="The main HTML content of the station card"
                    ),
                ),
                (
                    "x_position",
                    models.IntegerField(
                        default=0,
                        help_text="X Coordinate in vw (e.g. 0, 100, 200). Negative moves the camera right.",
                    ),
                ),
                (
                    "y_position",
                    models.IntegerField(
                        default=0,
                        help_text="Y Coordinate in vh (e.g. 0, -150, -300). Negative moves the camera down.",
                    ),
                ),
                (
                    "width",
                    models.CharField(
                        default="100%",
                        help_text="CSS Width (e.g. '100%', '800px', 'max-content')",
                        max_length=50,
                    ),
                ),
                (
                    "max_width",
                    models.CharField(
                        default="1200px",
                        help_text="CSS Max Width (e.g. '1200px', '100%')",
                        max_length=50,
                    ),
                ),
                (
                    "height",
                    models.CharField(
                        default="auto",
                        help_text="CSS Height (e.g. 'auto', '80vh')",
                        max_length=50,
                    ),
                ),
                (
                    "max_height",
                    models.CharField(
                        default="90vh",
                        help_text="CSS Max Height (e.g. '90vh')",
                        max_length=50,
                    ),
                ),
                (
                    "padding",
                    models.CharField(
                        default="3rem",
                        help_text="CSS Padding (e.g. '2rem', '3rem 4rem')",
                        max_length=50,
                    ),
                ),
                (
                    "overflow_behavior",
                    models.CharField(
                        choices=[
                            ("auto", "Auto (Scroll if needed)"),
                            ("hidden", "Hidden (Cut off)"),
                            ("scroll", "Always Show Scrollbar"),
                            ("visible", "Visible (Bleed out)"),
                        ],
                        default="auto",
                        max_length=20,
                    ),
                ),
                (
                    "bg_color",
                    models.CharField(
                        default="rgba(15, 23, 42, 0.6)",
                        help_text="CSS Background Color/Gradient",
                        max_length=50,
                    ),
                ),
                (
                    "border_color",
                    models.CharField(
                        default="rgba(255, 255, 255, 0.1)",
                        help_text="CSS Border Color",
                        max_length=50,
                    ),
                ),
                (
                    "text_color",
                    models.CharField(
                        default="#f8fafc",
                        help_text="CSS Text Color (Hex/Rgba)",
                        max_length=50,
                    ),
                ),
                (
                    "animation_style",
                    models.CharField(
                        choices=[
                            ("dangle", "Hanging on Rope (Swing)"),
                            ("float", "Floating Gently (Up/Down)"),
                            ("pulse", "Glowing/Pulsing Aura"),
                            ("none", "No Animation"),
                        ],
                        default="dangle",
                        max_length=20,
                    ),
                ),
                (
                    "blur_backdrop",
                    models.CharField(
                        default="24px",
                        help_text="Backdrop blur amount (e.g. '24px', '0px' for none)",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Station Map Point",
                "verbose_name_plural": "Station Map Points",
                "ordering": ["order"],
            },
        ),
    ]
