# Generated by Django 6.0.3 on 2026-04-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_station"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="custom_css",
            field=models.TextField(
                blank=True,
                help_text="Add any custom raw CSS properties here (e.g. 'box-shadow: 0 0 50px red;'). Applied directly to the station card.",
                null=True,
            ),
        ),
    ]
