# Generated by Django 6.0.3 on 2026-04-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_station_custom_css"),
    ]

    operations = [
        migrations.AlterField(
            model_name="station",
            name="bg_color",
            field=models.CharField(
                default="#0f172a",
                help_text="Hex Color code for background (e.g. #0f172a)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="station",
            name="border_color",
            field=models.CharField(
                default="#ffffff",
                help_text="Hex Color code for border (e.g. #ffffff)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="station",
            name="text_color",
            field=models.CharField(
                default="#f8fafc",
                help_text="Hex Color code for text (e.g. #f8fafc)",
                max_length=50,
            ),
        ),
    ]
