# Generated by Django 6.0.3 on 2026-04-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_station_bg_color_alter_station_border_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="camera_speed",
            field=models.FloatField(
                default=0.05,
                help_text="Controls how fast the camera pans between stations (0.01 is extremely slow, 0.10 is very fast, default 0.05).",
            ),
        ),
    ]
