# Generated by Django 6.0.3 on 2026-04-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_sitesettings_camera_speed"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="mobile_bg_color",
            field=models.CharField(
                blank=True,
                help_text="Mobile Background Hex Color. Blank uses desktop value.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="mobile_border_color",
            field=models.CharField(
                blank=True,
                help_text="Mobile Border Hex Color. Blank uses desktop value.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="mobile_custom_css",
            field=models.TextField(
                blank=True,
                help_text="Raw CSS to apply ONLY on screens smaller than 768px.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="mobile_height",
            field=models.CharField(
                blank=True,
                help_text="Mobile Height override (e.g. 'auto', '70vh'). Blank uses desktop value.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="mobile_max_height",
            field=models.CharField(
                blank=True,
                help_text="Mobile Max Height override (e.g. '85vh'). Blank uses desktop value.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="mobile_padding",
            field=models.CharField(
                blank=True,
                help_text="Mobile Padding override (e.g. '1.5rem'). Blank uses desktop value.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="mobile_text_color",
            field=models.CharField(
                blank=True,
                help_text="Mobile Text Hex Color. Blank uses desktop value.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="mobile_width",
            field=models.CharField(
                blank=True,
                help_text="Mobile Width override (e.g. '95vw', '100%'). Blank uses desktop value.",
                max_length=50,
                null=True,
            ),
        ),
    ]
