# Generated by Django 6.0.3 on 2026-04-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_station_mobile_bg_color_station_mobile_border_color_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="contact_recipient_email",
            field=models.EmailField(
                blank=True,
                help_text="Email address that receives contact form submissions",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="smtp_host",
            field=models.CharField(
                blank=True, help_text="e.g. smtp.gmail.com", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="smtp_password",
            field=models.CharField(
                blank=True,
                help_text="SMTP Password or App Password",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="smtp_port",
            field=models.IntegerField(default=587),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="smtp_use_tls",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="smtp_user",
            field=models.CharField(
                blank=True, help_text="SMTP Username", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="contact_recipient_email",
            field=models.EmailField(
                blank=True,
                help_text="Email address that receives contact form submissions",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="smtp_host",
            field=models.CharField(
                blank=True, help_text="e.g. smtp.gmail.com", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="smtp_password",
            field=models.CharField(
                blank=True,
                help_text="SMTP Password or App Password",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="smtp_port",
            field=models.IntegerField(default=587),
        ),
        migrations.AddField(
            model_name="station",
            name="smtp_use_tls",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="station",
            name="smtp_user",
            field=models.CharField(
                blank=True, help_text="SMTP Username", max_length=255, null=True
            ),
        ),
    ]
