# Generated by Django 6.0.3 on 2026-04-22 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_contactmessage_sitesettings_contact_recipient_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="station",
            name="contact_recipient_email",
        ),
        migrations.RemoveField(
            model_name="station",
            name="smtp_host",
        ),
        migrations.RemoveField(
            model_name="station",
            name="smtp_password",
        ),
        migrations.RemoveField(
            model_name="station",
            name="smtp_port",
        ),
        migrations.RemoveField(
            model_name="station",
            name="smtp_use_tls",
        ),
        migrations.RemoveField(
            model_name="station",
            name="smtp_user",
        ),
    ]
