# Generated by Django 6.0.3 on 2026-04-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_station_contact_recipient_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="freeze_on_hover",
            field=models.BooleanField(
                default=False,
                help_text="If checked, the animation (dangle, float, pulse) will pause/freeze while the user's mouse is hovering over the section.",
            ),
        ),
    ]
