# Generated by Django 6.0.3 on 2026-04-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_station_freeze_on_hover"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="site_name",
            field=models.CharField(default="SS's Blogs", max_length=100),
        ),
    ]
