# Generated by Django 6.0.3 on 2026-04-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_station_freeze_on_hover"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="mobile_overflow_behavior",
            field=models.CharField(
                choices=[
                    ("auto", "Auto (Scroll if needed)"),
                    ("hidden", "Hidden (Cut off)"),
                    ("scroll", "Always Show Scrollbar"),
                    ("visible", "Visible (Bleed out)"),
                ],
                default="auto",
                help_text="Overflow behavior specifically on mobile screens.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="station",
            name="overflow_behavior",
            field=models.CharField(
                choices=[
                    ("auto", "Auto (Scroll if needed)"),
                    ("hidden", "Hidden (Cut off)"),
                    ("scroll", "Always Show Scrollbar"),
                    ("visible", "Visible (Bleed out)"),
                ],
                default="auto",
                help_text="Overflow behavior on desktop screens.",
                max_length=20,
            ),
        ),
    ]
