# Generated by Django 6.0.3 on 2026-05-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_station_mobile_overflow_behavior_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="tawk_to_property_id",
            field=models.CharField(
                blank=True,
                help_text="Enter your Tawk.to Property ID to enable live chat (e.g. 60d5b4a...). Leave blank to disable.",
                max_length=100,
                null=True,
            ),
        ),
    ]
