# Generated by Django 6.0.3 on 2026-04-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_station_mobile_overflow_behavior_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="seo_description",
            field=models.TextField(
                blank=True, help_text="Overrides the default meta description"
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="seo_keywords",
            field=models.CharField(
                blank=True,
                help_text="Overrides the default meta keywords",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="seo_og_image",
            field=models.ImageField(
                blank=True,
                help_text="Overrides the default OG image",
                null=True,
                upload_to="seo_images/per_page/",
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="seo_title",
            field=models.CharField(
                blank=True, help_text="Overrides the default meta title", max_length=255
            ),
        ),
    ]
