# Generated by Django 6.0.3 on 2026-05-22 11:48

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_sitesettings_tawk_to_property_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="station",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(
                help_text="The main HTML content of the station card",
                verbose_name="Text",
            ),
        ),
    ]
