# Generated by Django 6.0.3 on 2026-05-22 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_station_content"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="max_concurrent_logins",
            field=models.IntegerField(
                choices=[
                    (0, "Unlimited Logins (Default)"),
                    (1, "Single Login (Logs out previous device)"),
                    (2, "Double Login (Max 2 devices)"),
                ],
                default=0,
                help_text="Restrict how many active sessions a single user account can have simultaneously. If exceeded, the oldest session is destroyed.",
            ),
        ),
        migrations.CreateModel(
            name="UserActiveSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=40, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
