# Generated by Django 6.0.3 on 2026-04-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GlobalSEOSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(default="Shiva Services", max_length=255),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True, help_text="Default meta description for the site."
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated keywords.",
                        max_length=500,
                    ),
                ),
                (
                    "og_title",
                    models.CharField(
                        blank=True, help_text="Default Open Graph title", max_length=255
                    ),
                ),
                (
                    "og_description",
                    models.TextField(
                        blank=True, help_text="Default Open Graph description"
                    ),
                ),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        help_text="Default image when sharing the site on social media.",
                        null=True,
                        upload_to="seo_images/",
                    ),
                ),
                (
                    "twitter_card_type",
                    models.CharField(
                        choices=[
                            ("summary", "Summary"),
                            ("summary_large_image", "Summary Large Image"),
                        ],
                        default="summary_large_image",
                        max_length=50,
                    ),
                ),
                (
                    "twitter_site",
                    models.CharField(
                        blank=True, help_text="e.g., @shivaservices", max_length=100
                    ),
                ),
                (
                    "google_analytics_id",
                    models.CharField(
                        blank=True,
                        help_text="e.g., G-XXXXXXX or UA-XXXXX-Y",
                        max_length=50,
                    ),
                ),
                (
                    "google_search_console_verification",
                    models.CharField(
                        blank=True,
                        help_text="Google site verification code",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Global SEO Settings",
                "verbose_name_plural": "Global SEO Settings",
            },
        ),
    ]
